"""A small immutable-ish ``Money`` value type, built by hand, then again with ``@dataclass``.

``Money`` is the hand-rolled version: we write ``__init__``, ``add``, ``__eq__`` and
``__repr__`` ourselves so we can see exactly what they do. ``DataMoney`` is the same value type
written with ``@dataclass(frozen=True)``, which generates the boilerplate (and a working
``__hash__``) for us.
"""

from __future__ import annotations

from dataclasses import dataclass


class Money:
    """An amount in a single currency, e.g. 500 cents of ``"USD"``.

    We store whole cents (an ``int``) rather than a float, because floats can't represent money
    exactly. Two ``Money`` objects are equal when their amount and currency both match.
    """

    def __init__(self, amount: int, currency: str) -> None:
        self.amount = amount
        self.currency = currency

    def add(self, other: Money) -> Money:
        if self.currency != other.currency:
            raise ValueError(
                f"cannot add {self.currency} to {other.currency}"
            )
        return Money(self.amount + other.amount, self.currency)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Money):
            return NotImplemented
        return self.amount == other.amount and self.currency == other.currency

    def __repr__(self) -> str:
        return f"Money(amount={self.amount}, currency={self.currency!r})"


@dataclass(frozen=True)
class DataMoney:
    """The same value type, generated by ``@dataclass(frozen=True)``.

    ``frozen=True`` makes instances read-only (assigning to a field raises) and, because the
    fields can no longer change, lets the dataclass also generate a ``__hash__``. So
    ``DataMoney`` is usable as a dict key or set member, which ``Money`` is not.
    """

    amount: int
    currency: str

    def add(self, other: DataMoney) -> DataMoney:
        if self.currency != other.currency:
            raise ValueError(
                f"cannot add {self.currency} to {other.currency}"
            )
        return DataMoney(self.amount + other.amount, self.currency)
